
version: "3"
services:
    postgres:
      image: postgres
      ports:
        - "5432:5432"
      volumes:
        - ./sql/postgresql.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        POSTGRES_PASSWORD: ml4kdbpwd
        POSTGRES_DB: mlforkidsdb
        POSTGRES_USER: ml4kdbuser
        POSTGRES_HOST: ml4knet
        POSTGRES_PORT: 5432
      networks:
      - ml4knet
    ml4k:
      build: .
      environment:
        POSTGRESQLHOST: ml4knet
        POSTGRESQLPORT: 5432
        POSTGRESQLUSER: ml4kdbuser
        POSTGRESQLPASSWORD: ml4kdbpwd
        POSTGRESQLDATABASE: mlforkidsdb
        PORT: 3000
        HOST: localhost
      ports:
        - "8875:3000"
      networks:
        - ml4knet
      depends_on:
        - postgres

networks:
  ml4knet:
